workspace:
  base: /drone
  path: src

pipeline:
  build:
    image: ubuntu:xenial
    pull: true
    environment:
      # Change the following to reflect your local preferences
      - PACKAGE=thetis
      - THETIS_HOME=/drone/install
      - THETIS_GID=1000
      - THETIS_UID=1000
      - CC=mpicc
      - PETSC_CONFIGURE_OPTIONS="--download-mumps --download-scalapack --download-parmetis --download-metis"
      - GIT_SOURCE_DIR=/drone/src
    commands:
      # Bring the image up to date
      - apt-get -y update
      - apt-get -y dist-upgrade

      # Install dependencies for a single run of firedrake-install
      - apt-get -y install sudo python-minimal python-pip curl

      # Fail fast on lint errors
      - pip install -U flake8
      - pip install pep8-naming
      - cd $GIT_SOURCE_DIR
      - make lint
      - pip install virtualenv

      # Make a firedrake user to run the tests
      - mkdir $THETIS_HOME
      - groupadd -g $THETIS_GID thetis
      - useradd -d $THETIS_HOME -u $THETIS_UID -g $THETIS_GID thetis

      # Passwordless sudo: \072 is octal for :
      # Colon breaks the drone yaml parser
      - /bin/echo -e "thetis ALL=NOPASSWD\072 ALL\n" >> /etc/sudoers

      # Install firedrake
      - cd $THETIS_HOME
      - curl -O https://raw.githubusercontent.com/firedrakeproject/firedrake/master/scripts/firedrake-install
      - python ./firedrake-install --disable-ssh --minimal-petsc --adjoint
      - . ./firedrake/bin/activate
      - pip install -r $GIT_SOURCE_DIR/requirements.txt
      - pip install -e $GIT_SOURCE_DIR/

      # Activate the virtualenv
      - . firedrake/bin/activate
      # scipy for the adjoint tests
      - pip install scipy

      # We're going to run the tests as the thetis user, so get permissions right.
      - chown -R thetis.thetis $THETIS_HOME

      - cd $THETIS_HOME
      # Run tests as the thetis user, pushing in the current path.
      - sudo -EHu thetis env PATH="$PATH" py.test -n 4 -v $GIT_SOURCE_DIR/test/

      # Now the adjoint tests
      - sudo -EHu thetis env PATH="$PATH" py.test -n 2 -v $GIT_SOURCE_DIR/test_adjoint/
