sudo: false
notifications:
  irc:
    channels: "chat.freenode.net#firedrake"
    skip_join: true
    on_success: change
    on_failure: always
    template: "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} | %{build_url}"

language: python
python: "2.7"
addons:
  apt:
    packages:
        - build-essential
        - python-dev
        - git
        - mercurial
        - python-pip
        - python-scipy
        - libopenmpi-dev
        - openmpi-bin
        - libblas-dev
        - liblapack-dev
        - gfortran
        - libspatialindex-dev
os:
  - linux

cache:
  directories:
    - $HOME/install/firedrake/

env:
  global:
    - CC=mpicc
    - PETSC_CONFIGURE_OPTIONS="--download-mumps --download-scalapack --download-parmetis --download-metis"

before_install:
  - pip install -U pip
  - pip install -U virtualenv
  - pip install pep8-naming

install:
  - mkdir -p $HOME/install
  - pushd $HOME/install
  - curl -O https://raw.githubusercontent.com/firedrakeproject/firedrake/master/scripts/firedrake-install
  # Check for cached install
  - if [[ ! -f ./firedrake/bin/activate ]]; then python ./firedrake-install --disable-ssh --minimal-petsc --adjoint; fi
  - . ./firedrake/bin/activate
  - pip install pytest
  - popd
  - pip install -v -r requirements.txt
  # Make thetis visible, don't want to pip install it, because then it will be cached by travis
  - export PYTHONPATH=`pwd`:$PYTHONPATH
script:
  - make lint
  - py.test --travis -v test/
  - py.test --travis -v test_adjoint/
